const DATA_ACTION = {
    LOAD: 'REQUEST_DATA',
    LOAD_SUCCESS: 'RECIEVED_DATA',
    SET: 'SET_DATA',
    SET_SUCCESS: 'SET_DATA_SUCCESS',
    UPDATE: 'UPDATE_DATA',
    UPDATE_LOGS: 'UPDATE_LOGS_DATA',
};

export { DATA_ACTION };